### ISSUE TITLE
How to use your code with Palo Alto Firewall MIBS

### ISSUE THREAD

**Issue by micruzz82** [sleepinggenius2/gosmi#12]
Hi @sleepinggenius2 this looks like a very useful tool. However I'm not a code and wanted to ask if there was any documentation on how to use this so I can convert Palo Alto firewall Mibs into the correct names?

Thank you for any help.

**Comment by sleepinggenius2** [comment]
I'm not sure that I fully understand your question, but I will do my best to respond. There is some basic example code under the *cmd* directory. I know there is a lack of comments in the code itself at the moment, but the standard godocs at https://pkg.go.dev/github.com/sleepinggenius2/gosmi should be fairly straightforward for using the library. It is still closely modeled around the C libsmi library, which it was originally a wrapper for. Personally, I don't generally use this library directly, but instead use my mib2go program to generate a Go representation of the MIBs that I need, then couple that with my snmpquery library to query equipment.
