### ISSUE TITLE
Issue reading Dell/EMC MIB files

### ISSUE THREAD

**Issue by xphyr** [sleepinggenius2/gosmi#13]
Good day.  First off, let me just say THANK YOU. This module is amazing and is helping out immensely with a project that I am working on. I have thrown a couple of MIBs at the library and it has worked exactly as I would expect. However I have come across a vendor whos MIBS do not seem to work. I have validated the MIBs with "snmptranslate" and they do work, but gosmi is not able to get the same data out of them.

An example MIB can be found here: http://doc.isilon.com/ECS/3.1/AdminGuide/ecs_r_snmp_oids_and_definition_of_enterprise_mib_ecs_mib.html
Interestingly I have tried multiple MIBs from this vendor and they all seem to exhibit the same problem.

If I use snmptranslate I get valid data back for a lookup of OIDs.  For example ".1.3.6.1.4.1.1139.102.1.1", however if I use the example code cmd/smi the only thing I get is the very beginning of the tree "1,3,6,1,4,1,1139" and it stops there. Given that other vendors MIBS are working just fine, I am guessing there is something different/special about this EMC one.

Any thoughts on what might be going on, or how to approach trying to figure it out. I am still a Go novice but willing to help and learn.

**Comment by sleepinggenius2** [comment]
Unfortunately, I do not see anything immediately obvious, but there is definitely something weird going on. At a quick glance, the file looks like it's being parsed properly, but the module does not seem to be getting built out correctly. I will certainly dig into this more and get back to you with my findings.

**Comment by sleepinggenius2** [comment]
It looks like there was already a pull request to address this issue. I have merged it and confirmed that the example MIB provided now appears to build correctly. Please let me know if you are still experiencing an issue with v0.3.2. Thanks.

**Comment by xphyr** [comment]
Thank you! That seems to have worked well. I will do some more testing, but initial tests look good. 

On a separate topic, I was thinking about helping out with documentation (if you would like), and was going to try and write up docs based on what I can find in libsmi since they seem very similar.  Would this be of help? Would you like me to open a new issue for this to discuss?

**Comment by sleepinggenius2** [comment]
Documentation and testing are certainly significant outstanding action items and I am open to any input the community would like to contribute in accomplishing those tasks. This library was originally a wrapper around libsmi, so the API that is now in the *smi* package is still very close. Please open a new issue to track.

**Comment by xphyr** [comment]
Thank you.  I will create a fork, and start some initial work on documentation, and will open a new issue to track this work.  Thank you for your quick reply and for this GREAT work!
