### ISSUE TITLE
Ask for an update in parser module cause parser fails to parse hex string in INTEGER syntax

### ISSUE THREAD

**Issue by MTamPham** [sleepinggenius2/gosmi#18]
Hi there,

It's me again. I've faced a rare MIB file that contains hex string under Integer syntax type. Would it be much trouble for you to update the parser module to be something like this?

https://github.com/sleepinggenius2/gosmi/blob/5a282bd9212b9c5ea24992b687f5eaf35a644b34/parser/common.go#L122

```golang
Value string              `parser:"\"(\" @( \"-\"? Int | HexString ) \")\""`
```

Please find the line 111 in the attached as a reference. This MIB can be found online from [here](http://www.circitor.fr/Mibs/Mib/A/APRISAXE-TC-4RF.mib) too under the name "AprisaXECardType".

I look forward to hearing from you soon.
Cheers.
[4RF-APRISAXE-TC.zip](https://github.com/sleepinggenius2/gosmi/files/5349318/4RF-APRISAXE-TC.zip)

**Comment by sleepinggenius2** [comment]
I have some mixed feelings about this item. To start with, the syntax referenced is not valid ASN.1 for a Named Number. This syntax is also not supported by libsmi, which is what this project was based on. It does appear to be supported by Net-SNMP, but looking through the source code, it appears to be a side-effect of the way that parser is written and not necessarily intended.

The goal of this project is to be as standards-compliant as possible. I understand that not all vendors consistently adhere to those same standards while developing their MIBs, so concessions have been made for some proposed/draft standards, but I do not want to encourage that practice. I know that ultimately comes back on the end-user though and not the vendor and want to be cognizant of that.

I have looked through all the MIBs (thousands) currently in my collection and this is the only file that I see using this syntax. The change is also more extensive than just the line of code referenced, as it breaks the API for any code consuming that Value and expecting an integer. If it was more widespread, then I would be more inclined to include support, but I will not be doing that for this one-off at this time.

**Comment by MTamPham** [comment]
Thank you very much for your response.

Yeah, I can understand from your perspective. Let me take care of this.

Tam Pham
