### ISSUE TITLE
Couldn't get enough nodes in the MIB file

### ISSUE THREAD

**Issue by MTamPham** [sleepinggenius2/gosmi#20]
Hi @sleepinggenius2,

I tried to call gosmi.GetModule() on IEEE8021-TC-MIB but it didn't return me the node "ieee802dot1mibs" for some reason. It leads to some nodes in IEEE8021-Q-BRIDGE-MIB are missing too.

Could you please help me to have a look? I attached the MIB files for you to debug. Hope it would help.

Thanks in advance
Tam

[mibs.zip](https://github.com/sleepinggenius2/gosmi/files/6029771/mibs.zip)

**Comment by sleepinggenius2** [comment]
There is apparently a side-effect with the way that the IEEE MIBs specify the OID component names explicitly. I will need to do a little more investigation to see how to resolve the issue. For the time being, replacing
```
::= { org ieee(111) standards-association-numbers-series-standards(2)
        lan-man-stds(802) ieee802dot1(1) 1 1 }
```
with
```
::= { ieee802dot1mibs 1 }
```
in *IEEE8021-TC-MIB* seems to resolve the issue.

**Comment by MTamPham** [comment]
Hi

Thank you for your quick response. Let me try your approach and will get back to you soon.

Tam

**Comment by MTamPham** [comment]
Hi,

Your approach seems to work but I am running into the same issue on another MIB. Could you help me to bypass the situation?

[LLDP-MIB.txt](https://github.com/sleepinggenius2/gosmi/files/6042810/LLDP-MIB.txt)

Tam
