### ISSUE TITLE
smi.GetParentNode() seems to always return the Node and not the Parent

### ISSUE THREAD

**Issue by lparkes** [sleepinggenius2/gosmi#22]
Hi,
I'm using smi.GetParentNode() and it always seems to return the same node that I pass it as a parameter instead of that node's parent.

e.g. The following code
```go
node, _ := gosmi.GetNodeByOID(oid)
log.Printf("node name: %s::%s of %s", GetModule().Name, node.Name, node.Kind)
parent := gosmi.CreateNode(smi.GetParentNode(node.GetRaw()))
log.Printf("parent name: %s::%s of %s", parent.GetModule().Name, parent.Name, parent.Kind)
```

produces the output
> bug  2021/03/20 13:08:47 node name: IF-MIB::ifPhysAddress of Scalar
> bug  2021/03/20 13:08:47 parent name: IF-MIB::ifPhysAddress of Scalar

when I'm expecting it to produce the output 
> bug  2021/03/20 13:08:47 node name: IF-MIB::ifPhysAddress of Scalar
> bug  2021/03/20 13:08:47 parent name: IF-MIB::ifEntry of Column

I couldn't help but notice that the smi.GetParentNode() function searches for the given node a lot, but never actually dereferences the Parent field. That's probably the problem. Those data structures are sufficiently complicated that I can't work out what the correct fix is. (Any data structure in any programming language that handles ASN.1 source seems to be complicated).

Cheers

**Comment by sleepinggenius2** [comment]
Your analysis is absolutely correct. New release coming your way momentarily.
