### ISSUE TITLE
oid with numbers and letters

### ISSUE THREAD

**Issue by MyaLongmire** [sleepinggenius2/gosmi#25]
I am using GetNode to find node with letters and numbers in the oid (ex .iso.2.3 or RFC1213-MIB::sysUpTime.0) but I am always getting could not find node. Is there a different function I should use?

**Comment by sleepinggenius2** [comment]
Just a heads up, .iso.2.3 does not exist; there is no ISO member body with a code of 3, so there should not be any MIB that would provide that OID.

I see in the libsmi documentation that:

> Node may be either a fully qualified descriptor, a simple node name, or a numerical OID. Nodes are also found, if node contains an instance identifier suffix.

Reviewing the code, it looks like simple node name is the only thing that is currently supported. I can certainly look at what it would take to add in the other options. As a workaround for the time being, replacing well-known iso with 1 and doing a search with GetNodeByOID should work for the .iso.2.3 case, but I don't have a good solution for a mix of numbers and identifiers without the identifier as the first arc in the OID. For the RFC1213-MIB::sysUpTime.0 form, splitting on :: and manually getting the module pointer for RFC1213-MIB, then running GetNode with the index-stripped identifier, like sysUpTime, should work. I understand that those are inherently fragile solutions and I have some idea of how the implementation might work, but it is going to take a little time to code out and test.

**Comment by MyaLongmire** [comment]
Thank you for your help and the quick reply. I will try to implement your workaround.
