### ISSUE TITLE
Is there a way to load just all available modules in paths?

### ISSUE THREAD

**Issue by ShyLionTjmn** [sleepinggenius2/gosmi#27]
Not sure which module going to be needed in the future, i want to just add it into directory and continue.

**Comment by sleepinggenius2** [comment]
If there is a directory in the path that contains an appropriately named MIB file for a needed import, then it will be loaded automatically. If you are looking to just load all the MIB files in a directory, then that shouldn't be too hard, but you will need to write that code yourself, as that functionality is not included out of the box at this time. I would generally discourage this approach though, as it is not typically the best approach for most applications. If your objective is to dynamically load a given module, then that would work just as you describe: put the file in a directory in the path and it will be available to load. If your objective is to translate OIDs into their more user-friendly object or notification form, then I would strongly recommend using the library to pre-process the data into a more appropriate and efficient form for your application to load at runtime.

**Comment by ShyLionTjmn** [comment]
Thanks
