### ISSUE TITLE
GetIndex

### ISSUE THREAD

**Issue by MyaLongmire** [sleepinggenius2/gosmi#28]
I am having an error when calling gosmi.GetIndex() saying it is not declared by gosmi. Can you please provide an example of how to use GetIndex().

**Comment by sleepinggenius2** [comment]
I'm assuming you're referring to this function:

https://github.com/sleepinggenius2/gosmi/blob/841095eac905c34222076a761d6d534d1fc8fef6/table.go#L109

If so, that method needs to be called on a row node (SmiNode with Kind==types.NodeRow) or table node (SmiNode with Kind==types.NodeTable).

**Comment by MyaLongmire** [comment]
Say I run `snmptranslate -Td IF-MIB::ifTable.1` and the output is
```
IF-MIB::ifEntry
ifEntry OBJECT-TYPE
  -- FROM	IF-MIB
  MAX-ACCESS	not-accessible
  STATUS	current
  INDEX		{ ifIndex }
  DESCRIPTION	"An entry containing management information applicable to a
            particular interface."
::= { iso(1) org(3) dod(6) internet(1) mgmt(2) mib-2(1) interfaces(2) ifTable(2) 1 }

```

how would I get the index so it would return ifIndex?

**Comment by MyaLongmire** [comment]
I figured it out.
