### ISSUE TITLE
RenderNumeric() coming back blank

### ISSUE THREAD

**Issue by MyaLongmire** [sleepinggenius2/gosmi#33]
I implemented the gosmi.GetModule like you recommened but RenderNumeric() keeps coming back blank. I have attached my program and the mib :)

Program as a txt file -> [synology.txt](https://github.com/sleepinggenius2/gosmi/files/7747904/synology.txt)
Mib file -> [SYNOLOGY-SYSTEM-MIB.txt](https://github.com/sleepinggenius2/gosmi/files/7747907/SYNOLOGY-SYSTEM-MIB.txt)

**Comment by sleepinggenius2** [comment]
When I run it on my system, I get an output of `1.3.6.1.4.1.6574.1.1`. If it's coming back blank, then the OID for that node is empty, which means it's disconnected. That MIB file looks fairly straightforward, so are you sure that you have the MIBs for SNMPv2-CONF and SNMPv2-SMI in your path?

**Comment by MyaLongmire** [comment]
I do have SNMPv2-CONF and SNMPv2-SMI in my path

**Comment by MyaLongmire** [comment]
It is the order of the files. I flip the order they are loaded in and it works.
