### ISSUE TITLE
Unable to get OID for some nodes

### ISSUE THREAD

**Issue by Hipska** [sleepinggenius2/gosmi#34]
Given the following files [comverse-comone-mib.my](https://github.com/sleepinggenius2/gosmi/files/7960310/comverse-comone-mib.my.txt) and [comverse-textual-notation.my](https://github.com/sleepinggenius2/gosmi/files/7960311/comverse-textual-notation.my.txt)

When doing

```golang
func main() {
	gosmi.Init()
	gosmi.SetPath("../../mibs")
	module, _ := gosmi.LoadModule("comverse-comone-mib.my")
	m, _ := gosmi.GetModule(module)
	trapNodes := m.GetNodes(types.NodeNotification)
	for _, node := range trapNodes {
		log.Printf("Trap %s::%s [%s]\n", module, node.Name, node.Oid)
	}
}
```

I'm getting this result:

> 2022/01/28 17:04:55 Trap COMVERSE-COMONE::upAlarmListRebuild []
> 2022/01/28 17:04:55 Trap COMVERSE-COMONE::upAlarmNew []
> 2022/01/28 17:04:55 Trap COMVERSE-COMONE::upAlarmChange []
> 2022/01/28 17:04:55 Trap COMVERSE-COMONE::upAlarmClear []

It's strange gosmi is able to find the nodes, but doesn't have the associated OID with them..

**Comment by sleepinggenius2** [comment]
Going up the OID tree for those notifications, I see that application is being imported from the COMVERSE-SNMP-OPEN-INTERFACE module. You will need to either explicitly load that module or make sure that a file with that name and optional .my, .mib, .mi2, or .txt extension is available in your search path.

**Comment by Hipska** [comment]
Yeah, that’s the other file. But would the nodes and names be able to be loaded if the other one isn’t?

**Comment by sleepinggenius2** [comment]
I only see where you're loading the one file and the name of the other file doesn't match the module name, so it won't be autoloaded. In the current library version, you would get exactly what you're seeing if an import cannot be satisfied. Starting in the next release, building the module will return an error in that case.

**Comment by Hipska** [comment]
Would be nice indeed if the methods return meaningful errors. Sadly it just prints to log or even stdout in some cases..

But thanks for the pointers, I will have a look..

**Comment by Hipska** [comment]
Closing as the OID gets filled when loading the other MIB first..
