### ISSUE TITLE
Panic from CreateTypeFromNode

### ISSUE THREAD

**Issue by bruceesmith** [sleepinggenius2/gosmi#4]
Hi

What a great library! Thank you!

I've come across a panic in C.GoString initiated from this line in CreateTypeFromNode

if format := C.GoString(smiNode.format); format != "" {

There is no check for smiNode.format being a null pointer (in smi.h the field is char *format inside SmiNode).

I suspect that the next part of this function which similarly calls C.GoString(smiNode.units) is susceptible to a similar problem.

I was parsing IF-MIB when this panic arose.

Regards
Bruce

**Comment by sleepinggenius2** [comment]
I apologize that I did not have my GitHub notifications configured properly and have only just seen this.

This wasn't an issue in earlier versions of Go, but seems to be now.  I ran into the same issue and I have now ditched libsmi entirely and written everything with a native Go implementation.
