### ISSUE TITLE
Compile failure with Go 1.11.1

### ISSUE THREAD

**Issue by bruceesmith** [sleepinggenius2/gosmi#5]
Hi

With Go 1.11.1 (and 1.11), there is a compilation error provoked by this line in smi.h:

typedef long double             SmiFloat128;

Error message is:

unexpected: 16-byte float type - long double

References: https://github.com/golang/go/issues/28069 and https://groups.google.com/forum/#!topic/golang-nuts/JnuXVK2lv_s

Very crude workaround: edit smi.h and comment out the 3 places where Smifloat128 is referenced (it is for SMing code in libsmi that will never be used in real life)

Regards
Bruce

**Comment by subcon42** [comment]
I, too, am seeing this issue.

go version go1.11.1 linux/amd64

**Comment by neermitt** [comment]
any update on this?

**Comment by sleepinggenius2** [comment]
I apologize that I did not have my GitHub notifications configured properly and have only just seen this.

I recently ran into this same issue and tried a similar workaround, but could never get things to work quite right. I have now ditched libsmi entirely and written everything with a native Go implementation.
